<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="test" ignored="0" tests="2" failures="1" timestamp="21 一月 2021 08:46:56 GMT" time="25.614" errors="0">
  <testcase name="test1" time="1.624" classname="assertTest">
    <failure type="java.lang.AssertionError" message="expected [密码错误多次，你还有最后一次机会，如果还是不对，账号将被锁定一小时。] but found [×
账号或密码错误。]">
      <![CDATA[java.lang.AssertionError: expected [密码错误多次，你还有最后一次机会，如果还是不对，账号将被锁定一小时。] but found [×
账号或密码错误。]
at assertTest.test1(assertTest.java:55)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test2" time="1.976" classname="assertTest"/>
</testsuite>
